apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  labels:
    app: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: banking-container
          image: chandanyadavks/banking:latest   # change if your DockerHub name is different
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: banking-service
spec:
  type: NodePort
  selector:
    app: banking
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30090
